language: java

install: ./gradlew setupCIWorkspace
script:
 - chmod +X ./gradlew
 - ./gradlew build
 - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

env:
  global:
    TERM=dumb

sudo: false

cache:
  directories:
    - ./libs
    - $HOME/.gradle/caches